apiVersion : apps/v1
kind: Deployment
metadata:
  name: "fabmedicald01-b7f8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fabmedicald01-b7f8"
  template:
    metadata:
      labels:
        app: "fabmedicald01-b7f8"
    spec:
      containers:
        - name: "fabmedicald01-b7f8"
          image: "fabmedicald01.azurecr.io/fabmedicald01"
          ports:
          - containerPort: 3001