apiVersion: v1
kind: Service
metadata:
    name: "fabmedicald01-b7f8"
    labels:
        app: "fabmedicald01-b7f8"
spec:
    type: LoadBalancer
    ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
    selector:
        app: "fabmedicald01-b7f8"