on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - uses: azure/docker-login@v1
      with:
        login-server: fabmedicald01.azurecr.io
        username: ${{ secrets.acr_fabmedicald01_username }}
        password: ${{ secrets.acr_fabmedicald01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/content-web" -f  "content-web/Dockerfile" -t fabmedicald01.azurecr.io/fabmedicald01:${{ github.sha }} --label dockerfile-path=content-web/Dockerfile
        docker push fabmedicald01.azurecr.io/content-web:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_fabmedicald01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep fabmedical-d018d03 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace fabmedical-d018d03`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: fabmedical-d018d03
        container-registry-url: fabmedicald01.azurecr.io
        container-registry-username: ${{ secrets.acr_fabmedicald01_username }}
        container-registry-password: ${{ secrets.acr_fabmedicald01_password }}
        secret-name: fabmedicald0dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: fabmedical-d018d03
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          fabmedicald01.azurecr.io/fabmedicald01:${{ github.sha }}
        imagepullsecrets: |
          fabmedicald0dockerauth
